pipeline:
  name: nomad-test
  identifier: nomadtest
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build-binaries
        identifier: buildbinaries
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: checkout
                  identifier: checkout
                  spec:
                    shell: Sh
                    command: apt-get update; apt-get install -y sudo unzip zip
  variables:
    - name: OSTYPE
      type: String
      description: ""
      value: <+input>
    - name: go_machine_image
      type: String
      description: ""
      value: "&go_machine_image     ubuntu-2004:202111-02"
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: nomad
        build: <+input>
