pipeline:
  name: nomad-test
  identifier: nomadtest
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build-binaries
        identifier: buildbinaries
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: checkout
                  identifier: checkout
                  spec:
                    shell: Sh
                    command: apt-get update; apt-get install -y sudo unzip zip
              - step:
                  type: Run
                  name: make deps
                  identifier: make_deps
                  spec:
                    shell: Sh
                    command: make deps
              - step:
                  type: Run
                  name: install-buf
                  identifier: installbuf
                  spec:
                    shell: Sh
                    command: sudo ./scripts/vagrant-linux-priv-buf.sh
              - step:
                  type: Run
                  name: prepare ui cache
                  identifier: prepare_ui_cache
                  spec:
                    shell: Sh
                    command: |
                      git log -n 1 --pretty=format:%H ui > /tmp/ui-sha
              - step:
                  type: Run
                  name: restore compiled ui assets
                  identifier: restore_compiled_ui_assets
                  spec:
                    shell: Sh
                    command: |-
                      if [[ -f /tmp/ui-assets/bindata_assetfs.go ]]; then
                                    cp /tmp/ui-assets/bindata_assetfs.go ./command/agent/bindata_assetfs.go
                                    exit 0
                                  fi
                                  ./scripts/vagrant-linux-unpriv-ui.sh
                                  export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
                                  export PATH="$GOPATH/bin:/usr/local/go/bin:$PATH"
                                  . ~/.nvm/nvm.sh
                                  cd ui && yarn install --frozen-lockfile && cd ..
                                  JOBS=2 make ember-dist static-assets
                                  mkdir -p /tmp/ui-assets
                                  cp ./command/agent/bindata_assetfs.go /tmp/ui-assets/bindata_assetfs.go
  variables:
    - name: OSTYPE
      type: String
      description: ""
      value: <+input>
    - name: go_machine_image
      type: String
      description: ""
      value: "&go_machine_image     ubuntu-2004:202111-02"
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: nomad
        build: <+input>
