pipeline:
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: test-ui
        identifier: testui
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: yarn install
                  identifier: yarn_install
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: node:14.17.1
                    shell: Sh
                    command: cd ui && yarn install --frozen-lockfile
              - step:
                  type: Run
                  name: save_cache
                  identifier: save_cache
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: node:14.17.1
                    shell: Sh
                    command: cd ui && yarn run lint:<+matrix.deps>
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - ./ui/node_modules
                  failureStrategies: []
                  strategy:
                    matrix:
                      deps:
                        - js
                        - hbs
                      maxConcurrency: 1
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: test
        identifier: test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Vault
                  identifier: Install_Vault
                  spec:
                    shell: Sh
                    command: |-
                      set -x
                                  case "linux" in
                                    linux*)  os="linux" ;;
                                    darwin*) os="darwin" ;;
                                    msys*)   os="windows" ;;
                                    *)       echo "unknown os:" <+pipeline.variables.OSTYPE>; exit 1 ;;
                                  esac
                                  curl -SL --fail -o /tmp/vault.zip https://releases.hashicorp.com/vault/1.2.4/vault_1.2.4_linux_amd64.zip

                                  if [["linux" != "windows" ]]; then
                                    unzip -d /usr/local/bin /tmp/vault.zip
                                    rm -rf /tmp/vault*
                                  else
                                    rm -rf c:\Windows\vault.exe
                                    unzip /tmp/vault.zip -d "/c/Windows"
                                    rm -rf /tmp/vault*
                                  fi
    - stage:
        name: build-binaries
        identifier: buildbinaries
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: "build binaries "
                  identifier: checkout
                  spec:
                    connectorRef: DhrubajyotiDocker
                    image: docker.mirror.hashicorp.services/golang:1.19.3
                    shell: Sh
                    command: |+
                      NOMAD_SLOW_TEST=1
                          GOTESTSUM_JUNITFILE=“/tmp/test-reports/results.xml”
                          GOTESTSUM_JSONFILE=“/tmp/test-reports/testjsonfile.json”
                          # disable implicit git paging.  CircleCI runs commands with in a tty
                          # making git assume it’s an interactive session.
                          PAGER=“cat”
                          GIT_PAGER=“cat”
                          GOPATH="/go"

                      apt-get update; apt-get install -y sudo unzip zip
                      make deps
                      sudo -E PATH="$GOPATH/bin:/usr/local/go/bin:$PATH" make generate-structs

                      git log -n 1 --pretty=format:%H ui > /tmp/ui-sha

          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  variables:
    - name: OSTYPE
      type: String
      description: ""
      value: <+input>
    - name: go_machine_image
      type: String
      description: ""
      value: "&go_machine_image     ubuntu-2004:202111-02"
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: nomad
        build: <+input>
  identifier: nomadtest_Clone
  name: nomad-test - Clone
