pipeline:
  name: nomad-test
  identifier: nomadtest
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: nomad
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Consul
                  identifier: teststep
                  spec:
                    shell: Sh
                    command: |
                      set -x
                                  echo installing golang ${GOLANG_VERSION}
                                  case "${OSTYPE}" in
                                    linux*)  os="linux" ;;
                                    darwin*) os="darwin" ;;
                                    msys*)   os="windows" ;;
                                    *)       echo "unknown os: ${OSTYPE}"; exit 1 ;;
                                  esac
                                  if [[ "${os}" != "windows" ]]
                                  then
                                    sudo rm -rf << parameters.target_directory >>/go
                                    sudo mkdir -p << parameters.target_directory >>
                                    curl -SL --fail -o /tmp/golang.tar.gz https://dl.google.com/go/go${GOLANG_VERSION}.${os}-amd64.tar.gz
                                    sudo tar -C << parameters.target_directory >> -xzf /tmp/golang.tar.gz
                                    rm -rf /tmp/golang.tar.gz
                                  else
                                    rm -rf << parameters.target_directory >>/go
                                    mkdir -p <<parameters.target_directory >>
                                    curl -SL --fail -o /tmp/go.zip https://dl.google.com/go/go${GOLANG_VERSION}.windows-amd64.zip
                                    unzip -q -o /tmp/go.zip -d << parameters.target_directory >>
                                    rm -rf /tmp/go.zip
                                  fi
  variables:
    - name: OSTYPE
      type: String
      description: ""
      value: <+input>
    - name: go_machine_image
      type: String
      description: ""
      value: "&go_machine_image     ubuntu-2004:202111-02"
